//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.MatchingAccountUsers = new HashSet<MatchingAccountUser>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int GroupID { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<int> DayOfCutOffDate { get; set; }
        public Nullable<int> DayOfPaymentDueDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public int UserGroupID { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchingAccountUser> MatchingAccountUsers { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
